#!/usr/bin/env bash

BUNDLE_GEM__FURY__IO="$(bundle config gem.fury.io | grep 'Set for' | sed 's/\(.*: \)//' | sed 's/\"//g')"

docker build \
  --build-arg RAILS_ENV=production \
  --build-arg BUNDLE_GEM__FURY__IO=$BUNDLE_GEM__FURY__IO \
  -t invocaops/pre_deploy_checker:latest \
  .